### ISSUE TITLE
发现有个bug

### ISSUE THREAD

**Issue by Likj** [dylan-farm/Technical-collection#1]
马帮主你好，我看了你的my-promise  发现有个bug；你的promise；整体的设计思想，我理解的如下，
1；新建一个promise构造函数；内部有一些状态相关的 变量，callBack 方法等；
2；这个函数 被实例的时候，会执行 传入的函数； 并且给当前函数传入，callBack；
3；resolve callBack 执行的时候，改变构造函数内部的 status
4； reject callB 执行的时候 改变status；
5；给函数的原型，增加then； 根据实例的status  决定当前的状态；

问题是； 原生的promise  可创建一个异步函数， 将当前的函数执行，放到 微任务；
当前的马帮主的 函数  没有实现这个功能；如果传入的是个 同步函数，那么。then 的回掉 就将同步执行

**Comment by dylan-farm** [comment]
感谢烙铁
